package main

import (
	"fmt"
	"net/http"
	"strings"

	ds "github.com/starfederation/datastar-go/datastar"
)

const (
	DISABLE_CHARTS = false
)

type cardProps struct {
	Name  string
	Value any
	Unit  string
}

var cards = []cardProps{
	{"Throttle", 0, "%"},
	{"Grip", 0, "%"},
	{"TPS", 0, "%"},
	{"RPM", 0, "RPM"},
	{"Coolant", 0, "°C"},
}

type chartProps struct {
	Name        string
	Description string
}

var charts = []chartProps{
	{"TPS", "Throttle"},
	{"RPM", "Revolutions Per Minute"},
}

// IndexHandler is the main entrypoint for the UI
func IndexHandler(w http.ResponseWriter, _ *http.Request) {
	err := Templates.ExecuteTemplate(w, "index", map[string]interface{}{
		"cards":         cards,
		"chartsEnabled": !DISABLE_CHARTS,
		"tpsChartProps": chartProps{
			Name:        "TPS",
			Description: "Throttle Position Sensor",
		},
		"rpmChartProps": chartProps{
			Name:        "RPM",
			Description: "Revolutions Per Minute",
		},
	})
	if err != nil {
		fmt.Println(err)
		w.WriteHeader(http.StatusInternalServerError)
	}
}

// EventsHandler is called on page load and pushes page changes to the client via SSE,
// based on events generated by the Huskki input source (live / replay)
func EventsHandler(w http.ResponseWriter, r *http.Request) {
	sse := ds.NewSSE(w, r)

	_, ch, cancel := EventHub.Subscribe()
	defer cancel()

	for {
		select {
		case <-r.Context().Done():
			return
		case event := <-ch:
			updateFunc := generatePatch(event)
			err := updateFunc(sse)
			if err != nil {
				fmt.Println(err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
		}
	}
}

func buildUpdateChartScript(name string, x, y int) string {
	return fmt.Sprintf(`pushData("%s", %d, %d);`, strings.ToLower(name), x, y)
}

// generatePatch takes an event received from the event queue, iterates the cards that are displayed on the UI,
// and returns a closure that can be used to patch the client.
func generatePatch(event map[string]any) func(*ds.ServerSentEventGenerator) error {

	var writer = strings.Builder{}
	var funcs []func(generator *ds.ServerSentEventGenerator) error

	// For each card, see if we have an update and template a response
	for _, card := range cards {
		if value, ok := event[strings.ToLower(card.Name)]; ok {
			Templates.ExecuteTemplate(&writer, "card.value", cardProps{Name: card.Name, Value: fmt.Sprintf("%v", value)})
		}
	}

	// For each chart see if we have an update and form an SSE update function
	for _, chart := range charts {
		if DISABLE_CHARTS {
			continue
		}
		value, ok := event[strings.ToLower(chart.Name)]
		if !ok {
			continue
		}
		timestamp, ok := event["timestamp"]
		if !ok {
			continue
		}

		v, ok := value.(int)
		if !ok {
			continue
		}
		ts, ok := timestamp.(int)
		if !ok {
			continue
		}

		funcs = append(funcs, func(sse *ds.ServerSentEventGenerator) error {
			err := sse.ExecuteScript(buildUpdateChartScript(chart.Name, ts, v))
			return err
		})
	}

	// Main closure
	return func(sse *ds.ServerSentEventGenerator) error {
		// Patch UI elements
		if writer.String() != "" {
			err := sse.PatchElements(writer.String())
			if err != nil {
				return err
			}
		}

		// Exec client-side javascript
		for _, f := range funcs {
			err := f(sse)
			if err != nil {
				return err
			}
		}

		return nil
	}
}
